# Generated by Django 5.2.6 on 2025-09-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('foto', models.ImageField(upload_to='equipe_fotos/', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Historia_valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('imagem', models.ImageField(upload_to='sobre_nos_images/%Y/%m/%d/', verbose_name='Imagem')),
                ('valores', models.TextField(verbose_name='Valores')),
            ],
        ),
    ]
