<<<<<<< HEAD
# Generated by Django 5.2.6 on 2025-09-24 00:26
=======
# Generated by Django 5.2.6 on 2025-09-23 03:15
>>>>>>> c1cad967d3ce4b137b8adea0502a3051b22780ba

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
