# Generated by Django 5.2.6 on 2025-09-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nomeautoridade',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome de Autoridade'),
        ),
    ]
