# Generated by Django 5.2.6 on 2025-09-24 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Tag')),
                ('descricao', models.TextField(verbose_name='Descrição da Tag')),
                ('cor', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor da Tag (Hex)')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_criada', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('imagem', models.ImageField(default='static/media/blog_images/doctor.jpg', upload_to='blog_images/%Y/%m/%d/', verbose_name='Imagem')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Número de Visualizações')),
                ('autor', models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor(es)')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
        ),
    ]
