# Generated by Django 5.2.6 on 2025-09-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('bio', models.TextField(verbose_name='Biografia')),
                ('profile_picture', models.ImageField(upload_to='autor_imagens/', verbose_name='Foto de Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('data_criada', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Imagem')),
            ],
        ),
    ]
