# Generated by Django 5.2.6 on 2025-09-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_image_blogpost_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagem',
            field=models.ImageField(upload_to='blog_images/%Y/%m/%d/', verbose_name='Imagem'),
        ),
    ]
