# Generated by Django 5.2.6 on 2025-09-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='imagem',
            field=models.ImageField(upload_to='blog_images/%Y/%m/%d/'),
        ),
    ]
