# Generated by Django 5.2.6 on 2025-09-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_autor_alter_blogpost_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Tag')),
                ('descricao', models.TextField(verbose_name='Descrição da Tag')),
            ],
        ),
    ]
