# Generated by Django 5.2.6 on 2025-09-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='cor',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor da Tag (Hex)'),
        ),
    ]
