# Generated by Django 5.2.6 on 2025-09-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Visualizações'),
        ),
    ]
