# Generated by Django 5.2.6 on 2025-09-23 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='autor',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='autor',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Autor(es)'),
        ),
    ]
