# Generated by Django 5.2.6 on 2025-09-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpost_autor_blogpost_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagem',
            field=models.ImageField(default='core/static/media/blog_images/doctor.jpg', upload_to='blog_images/%Y/%m/%d/', verbose_name='Imagem'),
        ),
    ]
