# Generated by Django 5.2.6 on 2025-09-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogpost_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagem',
            field=models.ImageField(default='static/media/blog_images/doctor.jpg', upload_to='blog_images/%Y/%m/%d/', verbose_name='Imagem'),
        ),
    ]
